apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k2bridge.fullname" . }}-kusto-credentials
type: Opaque
data:
  {{ if .Values.settings.aadClientSecret }}aadClientSecret: {{ .Values.settings.aadClientSecret  | b64enc | quote }}{{ end }}
