// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.
// See LICENSE file in the project root for full license information.

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.
using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "TEMP", Scope = "member", Target = "~M:K2Bridge.Startup.Configure(Microsoft.AspNetCore.Builder.IApplicationBuilder,Microsoft.AspNetCore.Hosting.IWebHostEnvironment)")]
[assembly: SuppressMessage("Design", "CA1056:Uri properties should not be strings", Justification = "TEMP", Scope = "member", Target = "~P:K2Bridge.Models.IConnectionDetails.ClusterUrl")]
[assembly: SuppressMessage("Performance", "CA1815:Override equals and operator equals on value types", Justification = "Inherited functionality is enough", Scope = "type", Target = "~T:K2Bridge.Models.QueryData")]

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "TODO: complete docs", Scope = "type", Target = "~T:K2Bridge.Startup")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "Cannot be null", Scope = "member", Target = "~M:K2Bridge.CorrelationIdHeaderMiddleware.Invoke(Microsoft.AspNetCore.Http.HttpContext)~System.Threading.Tasks.Task")]

[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "TODO", Scope = "member", Target = "~M:K2Bridge.Controllers.MetadataController.Passthrough~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "TODO", Scope = "member", Target = "~M:K2Bridge.KustoDAL.KustoResponseParser.ReadDataResponse(System.Data.IDataReader)~Kusto.Data.Data.KustoResponseDataSet")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "TODO", Scope = "member", Target = "~M:K2Bridge.KustoDAL.LuceneHighlighter.GetHighlightedValue(System.String,System.Object)~System.String")]
[assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "TODO", Scope = "member", Target = "~M:K2Bridge.KustoDAL.LuceneHighlighter.MakeValueHighlighter(Lucene.Net.QueryParsers.QueryParser,System.String,System.String,System.String)~Lucene.Net.Search.Highlight.Highlighter")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "Generic ensure method", Scope = "member", Target = "~M:K2Bridge.Ensure.ConditionIsMet(System.Boolean,System.String,Microsoft.Extensions.Logging.ILogger)")]
[assembly: SuppressMessage("Usage", "CA2254:Template should be a static expression", Justification = "Generic ensure method", Scope = "member", Target = "~M:K2Bridge.Ensure.ConstructMessageAndThrowArgumentOrNullArgument``1(``0,System.String,System.String,Microsoft.Extensions.Logging.ILogger)")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1316:Tuple element names should use correct casing", Justification = "Kusto method doesn't have the right case.", Scope = "member", Target = "~M:K2Bridge.KustoDAL.KustoQueryExecutor.ExecuteQueryAsync(K2Bridge.Models.QueryData,K2Bridge.Models.RequestContext)~System.Threading.Tasks.Task{System.ValueTuple{System.TimeSpan,System.Data.IDataReader}}")]

[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~P:K2Bridge.Models.Response.Aggregations.BucketAggregate.Keyed")]
[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~P:K2Bridge.Models.Response.Aggregations.HistogramBucket.Keyed")]
[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~F:K2Bridge.KustoDAL.LuceneHighlighter.isHighlight")]
[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~F:K2Bridge.KustoDAL.LuceneHighlighter.disposedValue")]
[assembly: SuppressMessage("Performance", "CA1805:Do not initialize unnecessarily", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~P:K2Bridge.Models.Response.Metadata.FieldCapabilityElement.IsMetadataField")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Controllers.QueryController.CheckEncodingHeader")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1413:Use trailing comma in multi-line initializers", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.JsonConverters.AggregationContainerConverter.GetPrimaryAggregation(Newtonsoft.Json.Linq.JProperty,Newtonsoft.Json.JsonReader,Newtonsoft.Json.JsonSerializer)~K2Bridge.Models.Request.Aggregations.Aggregation")]
[assembly: SuppressMessage("Performance", "CA1834:Consider using 'StringBuilder.Append(char)' when applicable", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.ElasticSearchDSLVisitor.BuildSummarizableMetricsQuery(System.Collections.Generic.IEnumerable{K2Bridge.Models.Request.Aggregations.Aggregation})~System.String")]
[assembly: SuppressMessage("Performance", "CA1834:Consider using 'StringBuilder.Append(char)' when applicable", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.ElasticSearchDSLVisitor.Visit(K2Bridge.Models.Request.Aggregations.ExtendedStatsAggregation)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.JsonConverters.AggregationContainerConverter.GetPrimaryAggregation(Newtonsoft.Json.Linq.JProperty,Newtonsoft.Json.JsonReader,Newtonsoft.Json.JsonSerializer)~K2Bridge.Models.Request.Aggregations.Aggregation")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.JsonConverters.IQueryConverter.DeserializeBoolQuery(Newtonsoft.Json.Linq.JToken,Newtonsoft.Json.JsonSerializer)~K2Bridge.Models.Request.Queries.BoolQuery")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.KustoDataAccess.CombineValues(Newtonsoft.Json.Linq.JToken)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.RewriteRules.RewriteSearchRule.GetIndexNameFromPath(Microsoft.AspNetCore.Http.PathString)~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.RewriteRules.RewriteTrailingSlashesRule.RewritePath(Microsoft.AspNetCore.Http.PathString)~Microsoft.AspNetCore.Http.PathString")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.ElasticSearchDSLVisitor.BuildMetadataQuery(System.Collections.Generic.Dictionary{System.String,System.Collections.Generic.List{System.String}})~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.ElasticSearchDSLVisitor.IsSimplePhrase(System.String)~System.Boolean")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.SchemaRetriever.MakeDictionary~System.Threading.Tasks.Task{System.Collections.IDictionary}")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.ElasticSearchDSLVisitor.FillKqlQuery(K2Bridge.Models.Request.Queries.RangeClause,System.Func{System.String,System.String})")]
[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.ElasticSearchDSLVisitor.Visit(K2Bridge.Models.Request.Queries.RangeClause)")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.KustoQueryExecutor.ExecuteQueryAsync(K2Bridge.Models.QueryData,K2Bridge.Models.RequestContext)~System.Threading.Tasks.Task{System.ValueTuple{System.TimeSpan,System.Data.IDataReader}}")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.KustoResponseParser.Parse(System.Data.IDataReader,K2Bridge.Models.QueryData,System.TimeSpan)~K2Bridge.Models.Response.ElasticResponse")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.KustoResponseParser.ReportQueryExecutionMetrics(Kusto.Data.Data.KustoResponseDataSet)")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.LuceneHighlighter.#ctor(K2Bridge.Models.QueryData,Microsoft.Extensions.Logging.ILogger)")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.LuceneHighlighter.GetHighlightedValue(System.String,System.Object)~System.String")]
[assembly: SuppressMessage("Naming", "CA1727:Use PascalCase for named placeholders", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.KustoDAL.LuceneHighlighter.MakeValueHighlighter(Lucene.Net.QueryParsers.QueryParser,System.String,System.String,System.String)~Lucene.Net.Search.Highlight.Highlighter")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters should be on same line or separate lines", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.DateMathParser.ParseDateMath(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1309:Use ordinal string comparison", Justification = "Will be fixed in a seperate PR", Scope = "member", Target = "~M:K2Bridge.Visitors.DateMathParser.ParseDateMath(System.String)~System.String")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Removing Collection from the name will cause other issues", Scope = "type", Target = "~T:K2Bridge.Models.Response.HitsCollection")]
